import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SocketProvider } from "@/components/providers/socket-provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { ToastContainer } from "react-toastify";
import { cn } from "@/lib/utils";

import ServerModalProvider from "@/components/providers/server-modal-provider";

import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
          <html lang="en">
              <body className={cn(inter.className, "bg-stone-50 dark:bg-stone-900/85 max-h-screen max-w-screen")}>
                  <ThemeProvider
                      attribute="class"
                      defaultTheme="dark"
                      enableSystem
                      disableTransitionOnChange
                  > 
                    <SocketProvider>
                      <ServerModalProvider />
                      <ToastContainer/>
                      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
                      {children}
                    </SocketProvider>
                  </ThemeProvider>
              </body>
          </html>
      </ClerkProvider>
  );
}
